---
- name: Configures mesh worker nodes - {{ track_slug }}
  hosts: localhost
  become: true
  gather_facts: false

  pre_tasks:
    - name: Include variable tasks
      vars:
        extra_vars:
          - name: track_slug
            env: TRACK_SLUG
          - name: redhat_username
            env: REDHAT_USERNAME
          - name: redhat_password
            env: REDHAT_PASSWORD
          - name: offline_token
            env: REDHAT_OFFLINE_TOKEN
          - name: gcp_service_account_file
            env: GCP_SERVICE_ACCOUNT_FILE
          - name: gcp_service_account
            env: GCP_SERVICE_ACCOUNT
          - name: gcp_instances
          - name: gcp_project
            env: GCP_PROJECT
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/60_check_vars.yml"

  tasks:
    - name: Include common user tasks
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/5_configure_users.yml"

    - name: Include common mesh worker node tasks
      vars:
        mesh_node_os_packages:
          - receptor
          - receptorctl
          - podman
          - crun
          - ansible-runner
          - libcgroup-tools
          - subscription-manager-rhsm-certificates
          - rsync
          - git
          - ansible
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/30_mesh_node.yml"

