galaxy_info:
  author: Craig Brandt
  description: Install TigerVNC for Instruqt labs
  license: Apache-2.0
  min_ansible_version: "2.9"

  platforms:
    - name: Fedora
      versions:
        - all
    - name: RHEL
      versions:
        - all

  galaxy_tags:
    - tigervnc
    - instruqt

dependencies: []
