- name: Jenkins config for devops-controller
  hosts: jenkins
  gather_facts: false

  vars:
    student_user: "student"
    student_password: "CHANGEME!"
    jenkins_template_file: "acme.xml"
    ansible_user: "ansible"


  tags:
    - jenkins-config

  tasks:
    - name: Wait for Jenkins to start up before proceeding.
      uri:
        url: "http://jenkins:8080/cli/"
        method: GET
        return_content: "yes"
        timeout: 5
        body_format: raw
        follow_redirects: "no"
        status_code: 200,403
      register: __jenkins_status
      until: (__jenkins_status.status == 403 or __jenkins_status.status == 200) and (__jenkins_status.content.find("Please wait while") == -1)
      retries: 5
      delay: 3
      changed_when: false

    - name: Install jenkins-cli
      ansible.builtin.get_url:
        url: http://jenkins:8080/jnlpJars/jenkins-cli.jar
        dest: /var/jenkins_home/jenkins-cli.jar
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"
      register: __jarfile_get
      until: "'OK' in __jarfile_get.msg or '304' in __jarfile_get.msg or 'file already exists' in __jarfile_get.msg"
      retries: 5
      delay: 10

    - name: Create Jenkins jobs
      ansible.builtin.shell:
        chdir: /var/jenkins_home
        cmd: "/opt/java/openjdk/bin/java -jar /var/jenkins_home/jenkins-cli.jar -s http://jenkins:8080 -auth {{ student_user }}:{{ student_password }} create-job "ACMECorp" < {{ jenkins_template_file }}"
      register: __output
      changed_when: __output.rc != 4
      failed_when: __output.rc not in [ 0, 4 ]