---
- name: check lab 2 challenge 2
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Enable service httpd, and not touch the state
      check_mode: true
      ansible.builtin.service:
        name: httpd
        state: started
      register: httpd_state

    - fail:
        msg: "http is not running"
      when: httpd_state.changed == True
