---
argument_specs:
  main:
    short_description: Set up the code server, main entrypoint.
    options:
      teardown:
        description: Whether to execute teardown or creation.
        type: bool
        required: true
      codserver+username:
        description: The workshop username.
        type: str
        required: true
      ec2_name_prefix:
        description: A prefix for EC2 and DNS resources.
        type: str
        required: true
      workshop_dns_zone:
        description: The base DNS zone for the workshop.
        type: str
        required: true
  codeserver:
    short_description: Provision the code server.
    options:
      s3_state:
        description: Whether the DNS record is present or absent.
        type: str
        options:
          - present
          - absent
        required: true
      workshop_dns_zone:
        description: The base DNS zone for the workshop.
        type: str
        required: true
      ec2_name_prefix:
        description: A prefix for EC2 and DNS resources.
        type: str
        required: true
      codesever_password:
        description: The code server admin password.
        type: str
        required: true
      codeserver_extensions:
        description: Code-server VSCode extensions to install
        type: list
        elements: string
        required: true
      codeserver_prebuild:
        description: Determine if this is an image pre_build
        type: bool
        required: true
      codeserver_authentication:
        description: Enable code-server authentication
        type: bool
        required: true
  teardown:
    short_description: Teardown the code server.
    options:
      s3_state:
        description: Whether the DNS record is present or absent.
        type: str
        options:
          - present
          - absent
        required: true
      workshop_dns_zone:
        description: The base DNS zone for the workshop.
        type: str
        required: true
      ec2_name_prefix:
        description: A prefix for EC2 and DNS resources.
        type: str
        required: true
      student_total:
        description: The total number of students for the workshop.
        type: int
        required: true
