---
- name: Setup vscode for web browser access
  ansible.builtin.include_tasks: "codeserver.yml"
  when: not codeserver_prebuild | bool

- name: Setup vscode everytime
  ansible.builtin.include_tasks: "codeserver_always.yml"
  when: codeserver_prebuild | bool
