slug: writing-first-playbook
id: z1eg1d9cwmzk
type: track
title: Writing your first playbook
teaser: Learn about the basics of how to write an Ansible playbook to automate simple
  infrastructure tasks
description: |-
  Ansible is a simple yet powerful IT automation engine for application deployment, configuration management, and orchestration that you can learn quickly. This exercise covers using Ansible to build Apache web servers on Red Hat Enterprise Linux.

  ![Lab diagram](https://ansible.github.io/workshops/images/rhel_lab_diagram.png)

  This exercise covers the following Ansible fundamentals:

  * Understanding Ansible Module parameters
  * Understanding and using the following modules
    * yum module
    * service module
    * copy module
  * Understanding Idempotence and how Ansible Modules can be idempotent


  You can find more information about Ansible at [Ansible.com](https://www.ansible.com/)

  [**Try Ansible Automation Platform today!**](https://red.ht/try_ansible)
icon: https://www.ansible.com/hubfs/Logo-Red_Hat-Ansible-A-Reverse-SVG.svg
tags:
- ansible
- infrastructure
- gettingstarted
owner: redhat
developers:
- moshah@redhat.com
private: false
published: true
show_timer: true
checksum: "15003613039669190742"
