slug: writing-first-playbook
id: z1eg1d9cwmzk
title: Write your first playbook
teaser: Learn the basics of writing a Red Hat Ansible Automation Platform playbook
  to automate simple infrastructure tasks.
description: |-
  Ansible is a simple yet powerful IT automation engine for application deployment, configuration management, and orchestration that you can learn quickly. This exercise covers using Ansible to build Apache web servers on Red Hat Enterprise Linux.

  ![Lab diagram](https://ansible.github.io/workshops/images/rhel_lab_diagram.png)

  This exercise covers the following Ansible fundamentals:

  * Understanding Ansible module parameters
  * Understanding and using the following modules
    * ansible.builtin.package module
    * ansible.builtin.service module
    * ansible.builtin.copy module
  * Understanding idempotence and how Ansible modules can be idempotent

  You can find more information about Ansible at [Ansible.com](https://www.ansible.com/)

  [**Try Ansible Automation Platform today!**](https://red.ht/try_ansible)
icon: https://www.ansible.com/hubfs/Logo-Red_Hat-Ansible-A-Reverse-SVG.svg
level: beginner
tags:
- ansible
- infrastructure
- gettingstarted
owner: redhat
developers:
- rlopez@redhat.com
- lgallego@redhat.com
show_timer: true
idle_timeout: 600
timelimit: 3300
lab_config:
  overlay: false
  width: 33
  position: right
  extend_ttl: 3300
checksum: "98958277858529269"
