---
- name: Listen for incoming webhook payload
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Forward git events to kafka
      condition: event.payload is defined
      action:
        run_playbook:
          name: playbooks/kafka_forward.yml