name: prod track test
on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
#   push:
#   pull_request:
  # Run CI once per day (at 06:00 UTC)
  # This ensures that even if there haven't been commits that we are still
  # testing. This is particularly important to validate the scenarios against
  # changes in ansible-core or ansible-test
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  get-instruqt-prod-tracks:
    runs-on: ubuntu-latest
    environment: test
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: get production tracks
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(curl https://play.instruqt.com/graphql \
          -H "Content-Type: application/json" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $INSTRUQT_API_KEY" \
          -d '{"query":"query tracks {\n  tracks(organizationSlug: \"redhat\") {\n    slug\n    maintenance\n  }\n}\n"' \
          | jq '.data.tracks[] | select(.maintenance==false) | .slug')
        env:
          INSTRUQT_API_KEY: ${{ secrets.INSTRUQT_API_KEY }}
          INSTRUQT_ORG: ${{ secrets.INSTRUQT_ORG }}
  
  run-track-test:
    runs-on: ubuntu-latest
    environment: test
    strategy:
      fail-fast: false
      matrix:
        track-slug: ${{ fromJson(needs.get-instruqt-prod-tracks.outputs.matrix) }}
        
    steps:
    - name: dump slugs
      run: echo ${{ matrix.track-slug }}
